---
  - name: Install EPEL on Red Hat systems
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    when:
      # This should work on both RHEL, CentOS, Scientific Linux, etc
      - ansible_distribution_file_variety == "RedHat"
      - ansible_distribution_major_version == "7"
